inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rails.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.4
  TargetRailsVersion: 5.1

# override method of onkcop
Style/StringLiterals:
  EnforcedStyle: single_quotes
Lint/AssignmentInCondition:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
